# Generated by Django 5.2.7 on 2025-10-30 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('organization', models.CharField(blank=True, max_length=255, verbose_name='Организация')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('request_type', models.CharField(choices=[('kp', 'КП'), ('consultation', 'Консультация'), ('support', 'Поддержка')], default='kp', max_length=20, verbose_name='Тип запроса')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Запрос КП',
                'verbose_name_plural': 'Запросы КП',
                'ordering': ['-created_at'],
            },
        ),
    ]
