# Generated by Django 5.2.7 on 2025-11-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, help_text='Описание изображения для поисковых систем и доступа', max_length=255, null=True, verbose_name='Alt-атрибут'),
        ),
    ]
