# Generated by Django 5.2.7 on 2025-11-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Описание изображения для поисковых систем и доступа', max_length=255, null=True, verbose_name='Alt-атрибут изображения'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_image_alt',
            field=models.CharField(blank=True, help_text='Описание изображения для поисковых систем и доступа', max_length=255, null=True, verbose_name='Alt-атрибут главного фото'),
        ),
    ]
